trigger:
  - main

pool:
  name: "macbook"

variables:
  Major: "1"
  Minor: "0"
  Patch: $(Build.BuildId)
  buildVersion: "$(Major).$(Minor).$(Patch)"

steps:
  - task: UseDotNet@2
    displayName: "Setup dot net..- maybe remove"
    inputs:
      packageType: "sdk"
      version: "8.x"

  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: "build"
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Pubish"
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/*.csproj"
      arguments: "--configuration Release --output $(Build.ArtifactStagingDirectory)"

  - task: DotNetCoreCLI@2
    displayName: "Pack project with version $(buildVersion)"
    inputs:
      command: "pack"
      packagesToPack: "**/*.csproj"
      versioningScheme: "byBuildNumber"
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:PackageId=WallaHelloWorld.$(buildVersion)"

  - script: |
      echo "Version: $(Build.BuildNumber)"
    displayName: "Print Version to Console"

  - task: DotNetCoreCLI@2
    displayName: "Push to artifact feed"
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "e87fdb84-f489-4d53-b849-4c54fa99d27b/42bf8ed2-8699-4fc1-8346-1400e3499e54"

